plugins {
    id 'java'
    id 'org.springframework.boot' version '3.5.3'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.janitor.api'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

dependencies {
    // Spring Boot Starters
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'

    // Database Driver
    implementation 'org.postgresql:postgresql:42.7.7'

    // Apache Commons
    implementation 'org.apache.commons:commons-lang3:3.18.0'

    // JSON Web Token (JJWT)
    implementation 'io.jsonwebtoken:jjwt-api:0.11.5'
    runtimeOnly   'io.jsonwebtoken:jjwt-impl:0.11.5'
    runtimeOnly   'io.jsonwebtoken:jjwt-jackson:0.11.5'

    // Lombok (compile only + annotation processor)
    compileOnly          'org.projectlombok:lombok:1.18.38'
    annotationProcessor  'org.projectlombok:lombok:1.18.38'

    // Dev tools & Docker Compose support
    developmentOnly 'org.springframework.boot:spring-boot-devtools'

    // Testing
    testImplementation     'org.springframework.boot:spring-boot-starter-test'
    testImplementation     'org.springframework.security:spring-security-test'
    testRuntimeOnly        'org.junit.platform:junit-platform-launcher'
}


tasks.named('test') {
    useJUnitPlatform()
}
