version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: janitor-postgres
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB}'
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - janitor

  app:
    build: .
    container_name: janitor-api
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: '${SPRING_DATASOURCE_URL}'
      SPRING_DATASOURCE_USERNAME: '${SPRING_DATASOURCE_USERNAME}'
      SPRING_DATASOURCE_PASSWORD: '${SPRING_DATASOURCE_PASSWORD}'
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - janitor

volumes:
  pgdata:
    driver: local

networks:
  janitor:
    external: true
    name: janitor
