spring.application.name=janitor-api
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/janitor}  
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:janitor}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:janitorAPI220645}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true
server.port=8080

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=when_authorized

# generate the hibernated entities
spring.jpa.generate-ddl=true

# JWT secret key
# node -e "console.log(require('crypto').randomBytes(32).toString('hex'))"
token.expirationms=3600000
token.secret.key=198cfbb325641896f3190a15263263ef6bda2085b108b9a1ee73c0c11e8f516f